workflows:
  android-native:
    name: Build Movy Native Android App
    max_build_duration: 60
    environment:
      vars:
        GRADLE_TASK: "assembleRelease"
    scripts:
      - name: Fix permissions and build APK
        script: |
          echo "Setting gradlew as executable..."
          chmod +x ./gradlew
          echo "Running Gradle build..."
          ./gradlew $GRADLE_TASK
    artifacts:
      - app/build/outputs//*.apk
    publishing:
      email:
        recipients:
          - syedrizwan003@gmail.com 